---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-aloys-cn-v1-application
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
      - key: metadata.name
        operator: NotIn
        values:
          - kube-system
          - default
          - cert-manager
          - monitoring
          - kube-node-lease
          - kube-public
  name: mapplication-v1.kb.io
  rules:
  - apiGroups:
    - apps.aloys.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-aloys-cn-v1-application
  failurePolicy: Fail
  #特定namespace不受这个规则限制
  namespaceSelector:
    matchExpressions:
      - key: metadata.name
        operator: NotIn
        values:
          - kube-system
          - default
          - cert-manager
          - monitoring
          - kube-node-lease
          - kube-public
  name: vapplication-v1.kb.io
  rules:
  - apiGroups:
    - apps.aloys.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
